Repository rauc/rauc-hawkbit, pull requests merged in 2019-03, with the labels that each got.

#8 Use readchunk and fix timeouts
  rauc_hawkbit/ddi/client.py
  setup.py
Labels: bug, enhancement

#17 ddi/client.py: remove extra / between host and api_path
  rauc_hawkbit/ddi/client.py
  tests/test_client.py
Labels: bug

#19 README.rst: fix syntax highlighting in code-block
  README.rst
Labels: documentation
